<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>"Глубокое обучение". Продвинутый поток</b></h3>

<h2 style="text-align: center;"><b>Домашнее задание 2. Библиотека Numpy и линейная алгебра.
</b></h2>

---

In [1]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# Ваш код здесь
print(a.ndim, a.shape)
# ========
print(a)
print(b)

2 (100, 100)
[[0.78389425 0.41612796 0.6912167  ... 0.34022211 0.8362154  0.38421865]
 [0.6736229  0.93871592 0.51936866 ... 0.58294822 0.84885465 0.98322284]
 [0.45297456 0.75235598 0.08124362 ... 0.4026982  0.70366178 0.343895  ]
 ...
 [0.76190561 0.71096515 0.0771774  ... 0.83741804 0.50008999 0.85724705]
 [0.47536929 0.81977529 0.60367956 ... 0.20155735 0.53395415 0.96758675]
 [0.21704158 0.0068957  0.50824007 ... 0.76825589 0.5081635  0.70589187]]
[[0.56752417 0.35055122 0.00334296 ... 0.10510428 0.3655108  0.98820784]
 [0.62103957 0.32181156 0.91324601 ... 0.70607355 0.98829463 0.04233283]
 [0.03192392 0.7185307  0.34226097 ... 0.31482699 0.43203964 0.03872801]
 ...
 [0.65886852 0.57704007 0.38380601 ... 0.38928711 0.4643308  0.99671051]
 [0.6744538  0.45187126 0.88367086 ... 0.75203141 0.59068103 0.00393653]
 [0.36127308 0.71650305 0.12695205 ... 0.68520698 0.06618053 0.92351294]]


In [3]:
def mult(a, b):
    lst = []
    tmp = []
    x = 0.0
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(b.shape[0]):
                x += a[i][k]*b[k][j]
            tmp.append(x)
            x = 0.0
        print(tmp)
        lst.append(list(tmp))
        tmp = []
    print(lst)
  
    return lst

In [4]:
def np_mult(a, b):
    
  
    return np.dot(a,b)

In [5]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

Wall time: 25.9 ms


In [6]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

[19.578771200737556, 21.95381707499427, 26.21913294819897, 22.44248757357349, 22.058365228222335, 25.547395831669856, 27.74628616974993, 23.356487099461884, 23.35293261422236, 25.32867346081272, 23.667884829779858, 25.120515165899388, 24.463074298736665, 25.126266331187303, 22.73991715034331, 25.797087060652743, 24.085683627961384, 21.379406911680192, 26.207821687034205, 25.357411168559302, 25.52536504452293, 22.354567236510402, 28.025195202831597, 27.01825076522108, 23.062840323502826, 21.029033203885813, 25.085872710227406, 23.89053190212813, 24.412476334622976, 21.468297455786406, 27.78790442584029, 26.531743405138414, 24.886720495585408, 24.337606730013043, 26.5414473188392, 22.971472380233575, 25.601824350802566, 26.57261445776056, 24.97307272217541, 25.191014030210713, 24.06970073173745, 25.515800283843042, 25.16797299564218, 20.98961468447716, 24.315726399227685, 25.225348344884516, 26.25441259872103, 25.074240370430587, 25.386140159712575, 26.137616570606696, 21.46360956850965,

[23.280752173427505, 21.98859300391884, 26.59240489299717, 24.57216705086273, 23.734777556894443, 25.111675744995416, 30.375959496377302, 23.595514633738148, 23.47154235414673, 25.12340032246386, 25.320635090669498, 27.258784184931134, 23.535187080176865, 24.43167991650341, 23.256676759109524, 26.213875736425642, 26.58527010198124, 23.96799638208825, 27.981752272174532, 26.08212814905997, 26.582368905065607, 22.031136217774968, 29.190433229128033, 25.951097537659827, 23.212492246854936, 24.708814481796225, 25.958981897370712, 23.264191349982767, 24.153674945501354, 24.993580615573414, 30.045422366142407, 26.809174174257258, 27.476018708540227, 27.210157219797306, 27.346884122670193, 25.215742454769785, 26.963514985859923, 27.67711651915018, 26.21426229454425, 26.2004768562311, 28.55092821439874, 26.751145279262456, 25.642668498666918, 21.657126276392493, 24.897914304243425, 27.384579272537007, 28.552280161594844, 27.536349527271792, 27.32362011612288, 27.267787908484433, 22.37308791209

[21.164632578630926, 21.028566874447115, 24.626065451301592, 21.783819406924128, 22.555550624521516, 25.3434808770096, 25.78418738806208, 22.159715627329355, 21.548693880521363, 24.081107323939342, 23.01048655727448, 24.989712210018954, 22.952694084626142, 22.384560221957063, 21.704311802024836, 26.16205194241674, 23.918133140365516, 21.888515173973012, 25.916574887692505, 23.698894218537916, 23.23361046613914, 22.349674536122485, 27.925651462078083, 26.29396645840023, 24.2383096530182, 22.711613260228845, 24.38911555942115, 23.57531487387083, 22.804523071690657, 24.716843596651294, 27.077340874839358, 25.299106742686742, 24.59932490531821, 24.51219981538743, 23.436963609240433, 23.372698881392395, 26.269711219605824, 25.51700053547131, 25.439921134497187, 25.12349095253995, 23.553942561628368, 24.039600114403065, 23.905308348295165, 21.28338140725028, 23.30180071696648, 23.403851449019772, 26.182601099774857, 23.4282570092204, 25.253535529214982, 24.99374700616226, 21.504313542818956,

[22.611813929336126, 23.450803087714508, 25.479617113871683, 23.823351710356192, 24.483164004120074, 25.543160765839417, 27.490181223544393, 22.27481994186816, 22.663956924612087, 25.24880923100122, 23.74428870597363, 26.387180254899224, 24.72728043754132, 26.80697592181339, 23.611760368021628, 26.584025300520658, 24.79636682608072, 21.27877943840369, 27.733505888534133, 25.2480230179621, 26.1873410240266, 23.798268384860126, 28.77020752124172, 28.482925999934114, 25.41043478114093, 22.46190726098023, 25.735346317422614, 23.760748584250198, 26.15984818389694, 24.772719813459158, 28.514675498241417, 26.994021101045696, 23.285694871702766, 24.761045530417697, 25.98459152595113, 23.505950059792927, 26.025563353599917, 26.87749275001311, 25.955699607613298, 24.367270858797188, 24.219945813832403, 25.916109618780926, 24.129742438906803, 22.31270073066479, 25.11038960343344, 25.573700764899787, 25.568300840985785, 25.213702175184157, 27.324705127698767, 26.663444923051156, 23.53193933992782,

In [0]:
print(len(M1))

100


In [0]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.3347545291253482e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [0]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

In [0]:
def scalar_product(a,b):
    return <YOUR CODE>

In [0]:
def np_scalar_product(a,b):
    return <YOUR CODE>

In [0]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [0]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  <YOUR CODE>
  return <YOUR CODE>

In [0]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

In [0]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [0]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    return <YOUR CODE>

In [0]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 

%time S2 = np_sec_av(A)

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [0]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    <YOUR CODE>
    return <YOUR CODE>

In [0]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

### Задание 6

Задан двумерный массив $X$. Для каждой строчки массива $X$ необходимо сделать следующее преобразование.

Пусть дана строчка $x$. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (значение по умолчанию $a$=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив $x$ с преобразованным $x$ и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива $X$. Массив $X$ при этом должен остаться без изменений.


Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [0]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    <YOUR CODE>
    return <YOUR CODE>

In [0]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = np_transformation(X, 5)