<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>"Глубокое обучение". Продвинутый поток</b></h3>

<h2 style="text-align: center;"><b>Домашнее задание 2. Библиотека Numpy и линейная алгебра.
</b></h2>

---

In [0]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [0]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# Ваш код здесь
print(a.ndim, a.shape)
# ========
print(a)
print(b)

2 (100, 100)
[[0.95547342 0.01558297 0.67426836 ... 0.23920069 0.16160494 0.49542126]
 [0.21255274 0.52406005 0.61685947 ... 0.85316558 0.16606288 0.89321597]
 [0.97353162 0.93527396 0.28782501 ... 0.5108006  0.69976154 0.60215287]
 ...
 [0.89053583 0.95822722 0.38590457 ... 0.49238584 0.15500921 0.73463619]
 [0.90195033 0.032299   0.54339568 ... 0.83436131 0.18523083 0.57447406]
 [0.92886667 0.68534252 0.17400619 ... 0.4429097  0.07298218 0.70568171]]
[[0.22241882 0.31033016 0.96058383 ... 0.61699935 0.97140017 0.47581789]
 [0.97325262 0.63562227 0.19255846 ... 0.79651575 0.84578222 0.01500388]
 [0.05018988 0.24207703 0.10884959 ... 0.96577489 0.77427957 0.43800767]
 ...
 [0.69374965 0.33752807 0.69000799 ... 0.7611476  0.82366546 0.44652817]
 [0.39646334 0.78718475 0.38213684 ... 0.36122813 0.86820723 0.94396499]
 [0.48904391 0.92344241 0.70952265 ... 0.52736946 0.57931049 0.9155652 ]]


In [0]:
def mult(a, b):
    lst = []
    tmp = []
    x = 0.0
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(b.shape[0]):
                x += a[i][k]*b[k][j]
            tmp.append(x)
            x = 0.0
        print(tmp)
        lst.append(list(tmp))
        tmp = []
    print(lst)
  
    return lst

In [0]:
def np_mult(a, b):
    
  
    return np.dot(a,b)

In [0]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.1 ms, sys: 20 µs, total: 1.12 ms
Wall time: 1.13 ms


In [0]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

[21.617501798561868, 26.705353666606268, 21.667170163459268, 25.453374341524533, 22.165822731473796, 21.520707205018844, 20.073790231776115, 25.528951621890855, 23.232850462969584, 21.43095494210071, 24.58988972313283, 23.127381207023696, 23.996928018473263, 23.131254978319895, 20.84156911063092, 21.57364273604921, 23.26654609991028, 24.256773252973034, 25.6516446201606, 26.76383486472364, 24.21564809721084, 24.307500548526292, 22.5716353212465, 21.361178268123094, 21.878622130316774, 23.420465153822672, 22.161702096545202, 23.48334500576716, 21.370105381531296, 23.536178293748815, 23.21037173372334, 23.34454864523477, 22.586034482808383, 23.763451622212408, 23.586217589692666, 24.67371932301883, 24.084878509281097, 24.943880840470364, 22.8171314158979, 24.821615640413903, 23.57425421495787, 22.917582951022048, 21.74455066148797, 25.417952051714884, 24.28326610436526, 22.428261997922693, 24.836076643543784, 24.402919469918587, 22.385773395171945, 23.060200611350393, 25.57579433861585, 

In [0]:
print(len(M1))

100


In [0]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.3347545291253482e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [0]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

In [0]:
def scalar_product(a,b):
    return <YOUR CODE>

In [0]:
def np_scalar_product(a,b):
    return <YOUR CODE>

In [0]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [0]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  <YOUR CODE>
  return <YOUR CODE>

In [0]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

In [0]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [0]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    return <YOUR CODE>

In [0]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 

%time S2 = np_sec_av(A)

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [0]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    <YOUR CODE>
    return <YOUR CODE>

In [0]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

### Задание 6

Задан двумерный массив $X$. Для каждой строчки массива $X$ необходимо сделать следующее преобразование.

Пусть дана строчка $x$. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (значение по умолчанию $a$=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив $x$ с преобразованным $x$ и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива $X$. Массив $X$ при этом должен остаться без изменений.


Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [0]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    <YOUR CODE>
    return <YOUR CODE>

In [0]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = np_transformation(X, 5)